export const NEXT_SONG = "NEXT_SONG"
export const PREVIOUS_SONG = "PREVIOUS_SONG"
export const PICK_SONG = "PICK_SONG"
export const SET_PLAYING = "SET_PLAYING"
export const SET_SOUND = "SET_SOUND"
export const SET_PLAYLIST = "SET_PLAYLIST"